### ISSUE TITLE
how about the performance of this implement

### ISSUE THREAD

**Issue by WHJTC** [SparkJiao/SLQA#1]
hi SparkJiao, thank you for your work, could you report the performance of your implement of SLQA. Thanks!

**Comment by SparkJiao** [comment]
Well the current F1 score is less than 40 :(  and there must be some problems. But unfortunately I'm working on another model and temporarily I will not fix it.
Btw, the formulation in the paper is a little confusing in my opinion and if you have any thoughts just mail me. Thanks a lot.

**Comment by SparkJiao** [comment]
The performance is now 62 on CoQA without using any previous questions and answers. I think it's still good enough. I have some problem on formulations of prediction layer.  If you would like to help me, I'd very appreciate it!
