### ISSUE TITLE
Ceil performance on SQuADv1.1 of this model

### ISSUE THREAD

**Issue by l11x0m7** [SparkJiao/SLQA#3]
Hi, have you ever tried to run this model on SQuADv1.1 without elmo? I've tried QANet, RNet, BiDAF and my own models on this dataset without tricky data preprocessing and elmo, and all of these models can not behave much better than [EM 70, F1 80] on the dev set.

**Comment by SparkJiao** [comment]
Well I think it's difficult to reach 80 on F1 without ELMo.
But it may be helpful that someone has test the model on SQuAD1.1 with elmo and got EM 69.7 and F1 79.1.
I think the model is still need to be tuned for better hyper-parameters. So if you are free you could tune it by yourself.
Besides, you could find original implementation of BiDAF and BiDAF with self-attention in Allennlp's Github, so you could just try them to get good grades.

**Comment by SparkJiao** [comment]
Tricky data processing is part of the model, so I recommend to use all word features you could use.

**Comment by l11x0m7** [comment]
Thanks a lot. I'll try ELMo and other pre-trained presentations on my models. Hope it can make great progress. I'm now still stuck in 80 on F1 and 70 on EM(the best result I can reach without any pre-trained model).
