### ISSUE TITLE
Some confusion about output layer: does this paper use pointer network in output layer?

### ISSUE THREAD

**Issue by IrvingBei** [SparkJiao/SLQA#6]
Thanks for sharing, but there is some confusion about the output layer: does this paper use Pointer Network in the output layer?

**Comment by SparkJiao** [comment]
Yes. `P^s=q W P^T` where q is the vector of question and P is the matrix of the passage.

**Comment by IrvingBei** [comment]
Hi, Is P^s the starting position of the answer? If it's, and this paper is calculated by bilinear function. But in the next paragraph, using a Pointer network to predict the start and end position of the answer.

So, this confuses me, and what should I understand these two parts

thanks again!

**Comment by IrvingBei** [comment]
Hi, based on the probability in P^s, choose the largest number as the pointer to point the start position. Is that right

**Comment by SparkJiao** [comment]
> Hi, based on the probability in P^s, choose the largest number as the pointer to point the start position. Is that right

Yes


> Hi, Is P^s the starting position of the answer? If it's, and this paper is calculated by bilinear function. But in the next paragraph, using a Pointer network to predict the start and end position of the answer.
> 
> So, this confuses me, and what should I understand these two parts
> 
> thanks again!

In my opinion, the Pointer network is indeed the bilinear function.

**Comment by IrvingBei** [comment]
That makes it clear. Thank you very much
